model:
  model_name: 'M2NO'
  num_layer: 5
  in_channels: 2
  out_channels: 1
  c: 8
  k: 8
  grid_levels: [1, 1, 1, 2, 2, 2, 3]
  padding_mode: 'circular'
  bias: True
  base: 'legendre'
  initializer: 'xavier_normal'
  norm: True
  activation: 'gelu'
  resolution: 1024

data:
  dataset: 'BurgersTime'
  data_path: 'PathTo/1D_Burgers_Sols_Nu1.0.hdf5'
  start_x: 0
  end_x: 1
  in_t: 1
  out_t: 1
  duration_t: 10
  raw_resolution: [1024, 201]
  sample_resolution: [512, 1]
  train_ratio: 0.6
  valid_ratio: 0.2
  test_ratio: 0.2
  subset: False
  subset_ratio: 0.1
  normalize: False
  normalizer_type: 'PGN'

train:
  random_seed: 0
  cuda: True
  device: 0
  epochs: 500
  patience: -1
  eval_freq: 1
  train_batchsize: 512
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

eval:
  eval_batchsize: 512
  eval_resolution: [512, 1]

optimize:
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.0001
  momentum: 0.95

schedule:
  scheduler: 'StepLR'
  step_size: 100
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
