model:
  model_name: 'M2NO'
  num_layer: 5
  in_channels: 4
  out_channels: 2
  k: 4
  c: 4
  grid_levels: [3, 3, 2, 2, 1]
  padding_mode: 'circular'
  bias: True
  base: 'legendre'
  norm: True
  activation: 'gelu'
  resolutions: [128, 128]

data:
  dataset: 'DiffReact2d'
  data_path: "PathTo/2D_diff-react_NA_NA.h5"
  raw_resolution: [128, 128, 101]
  sample_resolution: [32, 32, 1]
  in_t: 1
  out_t: 1
  duration_t: 10
  start_x: -1
  end_x: 1
  start_y: -1
  end_y: 1
  train_ratio: 0.6
  valid_ratio: 0.2
  test_ratio: 0.2
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 0
  cuda: True
  device: 0
  epochs: 500
  patience: 50
  eval_freq: 1
  train_batchsize: 16
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100

eval:
  eval_batchsize: 16
  eval_resolution: [32, 32, 1]

optimize:
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.00001

schedule:
  scheduler: 'StepLR'
  step_size: 100
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
